// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "geminiApiKey": string;
      "geminiModel": string;
      "geminiModelList": string;
      "chatWindowX": number;
      "chatWindowY": number;
      "chatWindowWidth": number;
      "chatWindowHeight": number;
      "systemInstruction": string;
    };
  }
}
